version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: incident-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=incident_management
    networks:
      - app-network
    

  app:
    build: .
    container_name: incident-app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DB=incident_management
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JINA_API_KEY=${JINA_API_KEY}
      - CHROMA_DIR=/app/db/chroma
    volumes:
      - ./db/chroma:/app/db/chroma
      - ./knowledge_base:/app/knowledge_base
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge